#!/bin/bash

# Neovim files
cp -r ~/.config/nvim ~/dev/tools/dotfiles

# .bashrc
cp ~/.bashrc ~/dev/tools/dotfiles/home/.bashrc
cp -r ~/.oh-my-bash/custom/themes/customRR ~/dev/tools/dotfiles
cp ~/.fzf.bash ~/dev/tools/dotfiles/home/.fzf.bash

# wezterm
cp ~/.wezterm.lua ~/dev/tools/dotfiles/home/
