#!/bin/bash

# Neovim files
cp -r ~/.config/nvim ~/dev/tools/dotfiles

# .bashrc
cp ~/.bashrc ~/dev/tools/dotfiles/home/.bashrc
cp -r ~/.oh-my-bash/custom/themes/customRR ~/dev/tools/dotfiles
cp ~/.fzf.bash ~/dev/tools/dotfiles/home/.fzf.bash

# tmux
cp ~/.tmux.conf ~/dev/tools/dotfiles/home/.tmux.conf

# wezterm
cp ~/.wezterm.lua ~/dev/tools/dotfiles/home/

if [ -z "$1" ]
then
	echo "Enter a commit message"
else
	git --git-dir=/home/bradenhelmer/dev/tools/dotfiles/.git --work-tree=/home/bradenhelmer/dev/tools/dotfiles add .
	git --git-dir=/home/bradenhelmer/dev/tools/dotfiles/.git --work-tree=/home/bradenhelmer/dev/tools/dotfiles commit -am "$1"
	git --git-dir=/home/bradenhelmer/dev/tools/dotfiles/.git --work-tree=/home/bradenhelmer/dev/tools/dotfiles push
fi
