#!/bin/bash
# Collects config files and pushes them to github
mkdir -p home nvim

# Neovim files
cp ~/.config/nvim/init.lua ~/dev/tools/dotfiles/nvim/
cp -r ~/.config/nvim/lua ~/dev/tools/dotfiles/nvim/

# .bashrc
cp ~/.bashrc ~/dev/tools/dotfiles/home/.bashrc
cp ~/.oh-my-bash/themes/customRR/customRR.theme.sh ~/dev/tools/dotfiles//customRR.theme.sh
cp ~/.fzf.bash ~/dev/tools/dotfiles/home/.fzf.bash

# tmux
cp ~/.tmux.conf ~/dev/tools/dotfiles/home/.tmux.conf

# wezterm
cp ~/.wezterm.lua ~/dev/tools/dotfiles/home/

if [ -z "$1" ]
then
	echo "Enter a commit message"
else
	git --git-dir=/home/bradenhelmer/dev/tools/dotfiles/.git --work-tree=/home/bradenhelmer/dev/tools/dotfiles add .
	git --git-dir=/home/bradenhelmer/dev/tools/dotfiles/.git --work-tree=/home/bradenhelmer/dev/tools/dotfiles commit -am "$1"
	git --git-dir=/home/bradenhelmer/dev/tools/dotfiles/.git --work-tree=/home/bradenhelmer/dev/tools/dotfiles push
fi
