#!/bin/bash

# Script for setting up a new ubuntu machine

# 1. Update repositories and install deps
apt get update
apt install -y wget curl

# 2. Install .oh-my-bash 
bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)"
rm ~/.bashrc && mkdir -p ~/.oh-my-bash/themes/customRR && cp bash/customRR.theme.sh ~/.oh-my.bash/themes/customRR/
cp bash/.bashrc ~/
source ~/.bashrc

# 3. Install neovim and other depenencies
apt install -y neovim

# Vim plug
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

# Need to install node for COC to work
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
source ~/.bashrc
nvm use 17

# Install LLVM, clang, ccls
bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
apt install -y ccls

mkdir -p ~/.config/nvim && cp nvim/* ~/.config/nvim/

