#!/bin/bash

# 1. Update repositories and install deps
apt update
apt install -y wget curl net-tools

# 2. Install .oh-my-bash 
bash -c "$(curl -fsSL https://raw.githubusercontent.com/bradenhelmer/oh-my-bash/master/tools/install.sh)"
source ~/.bashrc

# Install build essential
apt install -y build-essential ninja-build

mkdir -p ~/.config/nvim && cp nvim/* ~/.config/nvim/



